---
- name: start blockchain named {{ blockchainName }} on startup
  cron: 
    name: "blockchain {{ blockchainName }}"
    state: present
    special_time: reboot
    job: "sleep 5 && /usr/local/bin/multichaind {{ blockchainName }} -daemon >> /home/ansible/.multichain/{{ blockchainName }}/autostart.log"
    user: ansible
  register: cronResult
